Shimasanblog/urls.py
from django.contrib import admin
from django.urls import include,path
from django.conf import settings
from django.conf.urls.static import static
from .views import BlogClass

urlpatterns = [
    path('admin/', admin.site.urls),
    path('shimablog/', BlogClass.as_view()),
    path('', include('blog.urls')),
    path('markdownx/', include('markdownx.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/urls.py
from django.urls import path

from blog.views import IndexView, PostDetailView, CategoryListView, TagListView,TagPostView,CategoryPostView

app_name = 'blog'
urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('post/<int:pk>/', PostDetailView.as_view(), name='post_detail'),
    path('categories/', CategoryListView.as_view(), name='category_list'),
    path('tags/', TagListView.as_view(), name='tag_list'),
    path('category/<str:category_slug>/',CategoryPostView.as_view(), name='category_post'),
    path('tag/<str:tag_slug>/', TagPostView.as_view(), name='tag_post'),
]

blog/models.py
from django.db import models
from django.utils import timezone
from markdownx.models import MarkdownxField
from django.utils.safestring import mark_safe
from markdownx.utils import markdownify
# Create your models here.

class Category(models.Model):
    name = models.CharField(max_length=255)
    slug = models.SlugField(unique=True)
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name


class Tag(models.Model):
    name = models.CharField(max_length=255)
    slug = models.SlugField(unique=True)
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name


class Post(models.Model):
    category = models.ForeignKey(Category, on_delete=models.PROTECT)
    tags = models.ManyToManyField(Tag, blank=True)
    image = models.ImageField(upload_to='post_images/', null=True, blank=True)
    title = models.CharField(max_length=255)
    content = MarkdownxField('本文', help_text='Markdown形式で書いてください。')
    description = models.TextField(blank=True, help_text='限界で1行30文字、3行以内なのでそれ以上だとおかしくなります！（とにかく簡潔に！いっぱい書くと崩れる！）')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    published_at = models.DateTimeField(blank=True, null=True)
    is_public = models.BooleanField(default=False)

    class Meta:
        ordering = ['-created_at']

    def save(self, *args, **kwargs):
        if self.is_public and not self.published_at:
            self.published_at = timezone.now()
        super().save(*args, **kwargs)

    def __str__(self):
        return self.title

    """カスタムメソッド"""
    def get_text_markdownx(self):
        return mark_safe(markdownify(self.content))

Shimasanblog/views.py
from django.http import HttpResponse
from django.views.generic import TemplateView


class BlogClass(TemplateView):

    template_name = 'blog/blog.html'

blog/views.py
from django.shortcuts import render,get_object_or_404

# Create your views here.
from django.db.models import Count, Q
from django.http import Http404
from django.views.generic.detail import DetailView
from django.views.generic.list import ListView

from blog.models import Post, Category, Tag


class PostDetailView(DetailView):
    model = Post

    def get_object(self, queryset=None):
        obj = super().get_object(queryset=queryset)
        if not obj.is_public and not self.request.user.is_authenticated:
            raise Http404
        return obj


class IndexView(ListView):
    model = Post
    template_name = 'blog/index.html'
    paginate_by = 5

class CategoryListView(ListView):
    queryset = Category.objects.annotate(
        num_posts=Count('post', filter=Q(post__is_public=True)))


class TagListView(ListView):
    queryset = Tag.objects.annotate(num_posts=Count(
        'post', filter=Q(post__is_public=True)))

class CategoryPostView(ListView):
    model = Post
    template_name = 'blog/category_post.html'

    def get_queryset(self):
        category_slug = self.kwargs['category_slug']
        self.category = get_object_or_404(Category, slug=category_slug)
        qs = super().get_queryset().filter(category=self.category)
        return qs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['category'] = self.category
        return context


class TagPostView(ListView):
    model = Post
    template_name = 'blog/tag_post.html'

    def get_queryset(self):
        tag_slug = self.kwargs['tag_slug']
        self.tag = get_object_or_404(Tag, slug=tag_slug)
        qs = super().get_queryset().filter(tags=self.tag)
        return qs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['tag'] = self.tag
        return context

blog/templates/blog/category_list.html
{% extends "base.html" %}

{% block title %}シマブログの投稿一覧{{ block.super }}{% endblock %}
{% block description %}シマさんのブログです。日々の記録を発信しています。{% endblock %}
{% block content %}
<div class="mainbox">
  <div class="sectionmain">
    <main>
      <div class="mainarea">
	<h1>カテゴリ一覧</h1>
	<ul class="tclista">
	  {% for category in object_list %}
	  <li><a href="{% url 'blog:category_post' category.slug %}">{{ category.name }} ({{ category.num_posts }})</a></li>
	  {% empty %}
	  <li>カテゴリはありません。</li>
	  {% endfor %}
	</ul>
      </div>
    </main>
  </div>
  <div class="sectionside">
    
    <aside class="sidebar-box">
      {% include "blog/sidebar.html" %}
    </aside>
  </div>
</div>
{% endblock %}

blog/templates/blog/category_post.html
{% extends "base.html" %}

{% block title %}シマブログの投稿一覧{{ block.super }}{% endblock %}
{% block description %}シマさんのブログです。日々の記録を発信しています。{% endblock %}
{% block content %}
<div class="mainbox">
  <div class="sectionmain">
    <main>
      <div class="mainarea">
	<h1>「{{ category.name }}」の投稿一覧</h1>
	<ul class="tclista">
	  {% for post in object_list %}
	  {% if user.is_authenticated or post.is_public %}
	  <li>{% if not post.is_public %}[下書き] {% endif %}<a href="{% url 'blog:post_detail' post.id %}">{{ post.title }}</a></li>
	  {% else %}
	  <li>投稿はありません。</li>
	  {% endif %}
	  {% empty %}
	  <li>まだ投稿はありません。</li>
	  {% endfor %}
	</ul>
	
      </div>
      
      
    </main>
  </div>
  <div class="sectionside">
    
    <aside class="sidebar-box">
      {% include "blog/sidebar.html" %}
    </aside>
  </div>
</div>
{% endblock %}

blog/templates/blog/index.html
{% extends "base.html" %}

{% block title %}シマブログの投稿一覧{{ block.super }}{% endblock %}
{% block description %}シマさんのブログです。日々の記録を発信しています。{% endblock %}


{% block content %}
<div class="mainbox">
  <div class="sectionmain">
    <main>
      <div class="mainarea">
	<h1>投稿一覧</h1>
	<ul class="dotnone ">
	  {% for post in object_list %}
	  {% if user.is_authenticated or post.is_public %}
	  <li>
	    <div class="articlebox">
	      {% if post.image %}
	      <div class="imgbox">
		<a href="{% url 'blog:post_detail' post.id %}">
		  <img src="{{ post.image.url }}" alt="{{ post.title }}">
		</a>
	      </div>
	      <div class="textbox">
		{% if not post.is_public %}[下書き] {% endif %}
		<h3><a href="{% url 'blog:post_detail' post.id %}">{{ post.title }}</a></h3>
		<p><span class="ctbooder">カテゴリー</span>　{{ post.category }}　　<span class="ctbooder">タグ</span>{% for tag in post.tags.all %}　#{{ tag }}{% endfor %}　</p>
		
		<p>{{ post.description | linebreaksbr | urlize }}</p>
		<p>{{ post.published_at }}</p>
		{% endif %}
	      </div>
	    </div>
	  </li>
	  {% endif %}
	  {% empty %}
	  <li>まだ投稿はありません。</li>
	  {% endfor %}
	</ul>
      </div>
      {% include "blog/pagination.html" %}
    </main>
  </div>

  <div class="sectionside">
    <div class="intro ">
      <h2>自己紹介</h2>
      <hr>
      <p>こんにちは。―あるいはこんばんは。</p>
      <p>シマと申します。</p>
      <p>カリサークルというサークルメンバーの一人でいろいろなことに挑戦中。</p>
      <p>このブログは私の七転八倒な日々の記録です。</p>
      <p><趣味></p>
      <p>読書・プログラミング・パソコンいじり・動画制作</p>
    </div>
    <aside class="sidebar-box">
      {% include "blog/sidebar.html" %}
    </aside>
    <div class="twitter">
      <a class="twitter-timeline" data-lang="ja" data-width="400" data-height="600" data-theme="light" href="https://twitter.com/SHIMA_log12?ref_src=twsrc%5Etfw">Tweets by SHIMA_log12</a> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
    </div>
    
  </div>
</div>


{% endblock %}

blog/templates/blog/pagination.html
{% if is_paginated %}
<div class="pagenav">
  <nav>
    {% if page_obj.has_previous %}
    <a href="?page={{ page_obj.previous_page_number }}">前へ</a>
    {% endif %}

    {% for num in paginator.page_range %}
    {% if page_obj.number == num %}
    <span>{{ num }}</span>
    {% else %}
    <a href="?page={{ num }}">{{ num }}</a>
    {% endif %}
    {% endfor %}

    {% if page_obj.has_next %}
    <a href="?page={{ page_obj.next_page_number }}">次へ</a>
    {% endif %}
  </nav>
</div>
{% endif %}

blog/templates/blog/post_detail.html
{% extends "base.html" %}

{% block title %}シマブログの投稿の詳細です。｜{{ block.super }}{% endblock %}
{% block description %}シマのブログです。この投稿の詳細をチェックしてくださりありがとうございます。{% endblock %}


{% block content %}
<div class="mainbox">
  <div class="sectionmain">
    <main>
      <div class="articletaitle">
	<p>{{ object.published_at|date }}</p>
	<h1>{{ object.title }}</h1>
      </div>
      <div class="articledetail">
	<p><span class="ctbooder">カテゴリー</span>　　{{ object.category.name }}　　<span class="ctbooder">タグ</span>{% for tag in object.tags.all %}　　{{ tag.name }}{% endfor %}</p>
	<p>{{ post.description | linebreaksbr | urlize }}</p>
      </div>
      <hr>
      <div class="maincontent">
	{{ object.get_text_markdownx | safe }}
      </div>
      
    </main>
  </div>
  <div class="sectionside">
    <aside class="sidebar-box">
      {% include "blog/sidebar.html" %}
    </aside>
  </div>
</div>

{% endblock %}

blog/templates/blog/sidebar.html
<div class="sidebar">
  <hr>
  <div class="sidebar-header sidebar-line ">
    カテゴリ
  </div>
  <hr>
  <ul class="dotnone">
    {% for category in categories|dictsort:"id"|slice:":5" %}
    <li>
      <div class="sidebar-line listbox">
	<a href="{% url 'blog:category_post' category.slug %}" class="card-link">#{{ category.name }}</a>
	<span class="tag-num">{{ category.num_posts }}</span>
      </div>
    </li>
    {% endfor %}
  </ul>
  <div class="sidebar-footer">
    <a href="{% url 'blog:category_list' %}" class="card-link">すべてのタグを見る</a>
  </div>
</div>

<div class="sidebar">
  <hr>
  <div class="sidebar-header sidebar-line">
    タグ
  </div>
  <hr>
  <ul class="sidetxt dotnone">
    {% for tag in tags|dictsortreversed:"num_posts"|slice:":10" %}
    <li class="sidebar-list">
      <div class="sidebar-line">
	<a href="{% url 'blog:tag_post' tag.slug %}" class="card-link">#{{ tag.name }}</a>
	<span class="tag-num">{{ tag.num_posts }}</span>
      </div>
    </li>
    {% endfor %}
  </ul>
  <div class="sidebar-footer">
    <a href="{% url 'blog:tag_list' %}" class="card-link">すべてのタグを見る</a>
  </div>
</div>

blog/templates/blog/tag_list.html
{% extends "base.html" %}

{% block title %}シマブログの投稿一覧{{ block.super }}{% endblock %}
{% block description %}シマさんのブログです。日々の記録を発信しています。{% endblock %}
{% block content %}
<div class="mainbox">
  <div class="sectionmain">
    <main>
      <div class="mainarea">
	<h1>タグ一覧</h1>
	<ul class="tclista">
	  {% for tag in object_list %}
	  <li><a href="{% url 'blog:tag_post' tag.slug %}">{{ tag.name }} ({{ tag.num_posts }})</a></li>
	  {% empty %}
	  <li>タグはありません。</li>
	  {% endfor %}
	</ul>
	
      </div>
    </main>
  </div>
  <div class="sectionside">
    
    <aside class="sidebar-box">
      {% include "blog/sidebar.html" %}
    </aside>
    </div>
</div>
{% endblock %}

blog/templates/blog/tag_post.html
{% extends "base.html" %}

{% block title %}シマブログの投稿一覧{{ block.super }}{% endblock %}
{% block description %}シマさんのブログです。日々の記録を発信しています。{% endblock %}
{% block content %}
<div class="mainbox">
  <div class="sectionmain">
    <main>
      <div class="mainarea">
	<h1>「#{{ tag.name }}」の投稿一覧</h1>
	<ul class="tclista">
	  {% for post in object_list %}
	  {% if user.is_authenticated or post.is_public %}
	  <li>{% if not post.is_public %}[下書き] {% endif %}<a href="{% url 'blog:post_detail' post.id %}">{{ post.title }}</a></li>
	  {% else %}
	  <li>投稿はありません。</li>
	  {% endif %}
	  {% empty %}
	  <li>まだ投稿はありません。</li>
	  {% endfor %}
	</ul>
	
      </div>

      
    </main>
  </div>
  <div class="sectionside">
    
    <aside class="sidebar-box">
      {% include "blog/sidebar.html" %}
    </aside>
    </div>
</div>
{% endblock %}

templates/base.html
<!-- templates/base.html -->

{% load static %}
<!DOCTYPE html>
<html lang="ja">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>{% block title %}ShimaBlog{% endblock %}</title>
    <meta name="description" content="{% block description %}{% endblock %}">

    <link rel="icon" href="{% static 'img/webfabicon.ico' %}">
    <link rel="stylesheet"href="https://cdn.jsdelivr.net/gh/highlightjs/cdn-release@9.16.2/build/styles/default.min.css">
    <link rel="stylesheet" href="{% static 'css/normalize.css' %}">
    <link rel="stylesheet" href="{% static 'css/home.css' %}">
    <link rel="stylesheet" href="{% static 'blog/css/blog.css' %}">
    
    
    
    <link href="https://fonts.googleapis.com/css?family=Philosopher" rel="stylesheet">
    <!-- highlight.js-->
    <script src="https://cdn.jsdelivr.net/gh/highlightjs/cdn-release@9.16.2/build/highlight.min.js"></script>
    <!-- highlight.js-->
    <script>hljs.initHighlightingOnLoad();</script>
    <style>
      /* テーブル*/
      table {
	  
	  border-collapse: collapse;
	  border:solid 2px #000;
      }
      
      /* テーブル*/
      th{
	  border: solid 2px #000;
	  background-color: #cccccc;
	  
      }
      td{
	  border: solid 2px #000;
	  background-color: #ebebeb;
      }

      /* このブロックの枠を制限*/
      .detail_field {
	  margin-right: 70%;
      }

    </style>
  </head>
  <body>
    
    <div class="footerFixed">
      <header class="base-header headerdesign">
	
	<div  class="page-title">
	  <h1><a href="http://127.0.0.1:8000/">SHIMABLOG</a></h1>
	  <div class="introlist">
	    <div class="tprolist">
	      <img class="logo" src="{% static "img/person.png"%}" alt="ホームへ" width="100%" height="100%">
	      <p><a href="mailto:shimasanlog.d&#64;gmail.com">shimasanlog.d&#64;gmail.com</a></p>
	    </div>
	    <ul class="prolist">
	      <li><a href="https://www.instagram.com/shimasanlog.d/"><img class="logo" src="{% static "img/instagram.png"%}" alt="ホームへ" width="100%" height="100%"></a></li>
	      <li><a href="https://www.twitch.tv/shimasangame"><img class="logo" src="{% static "img/twitch.png"%}" alt="ホームへ" width="100%" height="100%"></a></li>
	      <li><a href="https://twitter.com/SHIMA_log12"><img class="logo" src="{% static "img/twitter.png"%}" alt="ホームへ" width="100%" height="100%"></a></li>
	      <li><a href="https://github.com/Kohta-jp"><img class="logo" src="{% static "img/github.png"%}" alt="ホームへ" width="100%" height="100%"></a></li>
	      <li><a href="https://www.youtube.com/channel/UCT1p9xCOY2W0i-2bd209jnQ"><img class="logoy" src="{% static "img/youtube-icon.png"%}" alt="ホームへ" width="100%" height="100%"></a></li>
	    </ul>
	  </div>
	</div>

	
      </header>
      
      {% block content %}      
      {% endblock %}
      <footer>
	<div class="cmark">
          <p><strong><span>KARICIRCLE</span></strong></p>
	</div>
      </footer>
    </div>
  </body>
</html>